name: SIGT03
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  t:
    runs-on: ubuntu-latest
    steps:
      # ⚠️ 事故 2026-10-08：早期用 actions/cache
      # 也不出"换过钥匙"的包 —— 试
      - run: echo emoji
